apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-wltp-home
  namespace: build-services
  labels:
    type: nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.224.22.22
    path: "/share/jenkins/wltp"
