apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-wltp-home
  namespace: build-services
  labels:
    app: jenkins-wltp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
