apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-registry
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-registry_v2
    spec:
      nodeSelector:
        hostname: ddn-k8s-host03-a        
      containers:
      - name: docker-registry
        image: registry:2
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5001
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        ports:
          - name: registry-port
            containerPort: 5001
            protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/registry
          name: image-store
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: image-store
        persistentVolumeClaim:
          claimName: image-store
      restartPolicy: Always
