apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-store
  namespace: default
  labels:
    type: nfs
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.224.22.22
    path: "/share/docker-registry"
