apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-store
  namespace: default
  labels:
    app: docker-registry_v2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
