apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: default
spec:
  ports:
  - port: 5001
    name: registry-port
    protocol: TCP
    targetPort: 5001
  selector:
    app: docker-registry_v2
  sessionAffinity: None
  externalIPs:
  - 10.224.22.10
