apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus:oss
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: sonatype-work
              mountPath: /sonatype-work
      volumes:
        - name: sonatype-work
          persistentVolumeClaim:
            claimName: sonatype-work
