apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonatype-work
  namespace: nexus
  labels:
    app: nexus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
