apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-etc
  namespace: gitlab
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.224.22.22
    path: "/share/gitlab/etc"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data
  namespace: gitlab
  labels:
    type: nfs
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.224.22.22
    path: "/share/gitlab/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs
  namespace: gitlab
  labels:
    type: nfs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.224.22.22
    path: "/share/gitlab/logs"
