apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs-reconfigure
  namespace: gitlab
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.224.22.22
    path: "/share/gitlab/logs/reconfigure"
