apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs-reconfigure
  namespace: gitlab
  labels:
    app: gitlab
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi