global:
#  smtp_smarthost: 'aa.softlab.de:25'
  smtp_smarthost: '10.224.22.5:8025'
  smtp_from: 'michael.temmen@nttdata.com'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
    - to: 'michael.temmen@nttdata.com'
      require_tls: false
