apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data
  namespace: sonar
  labels:
    type: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.224.22.22
    path: "/share/sonar/db-data"
