apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: sonar
  labels:
    app: sonarqube
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
