apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-swt-home
  namespace: build-services
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.224.22.22
    path: "/share/jenkins/swt"
