apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-swt-home
  namespace: build-services
  labels:
    app: jenkins-infrastructure
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
