apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache2
  namespace: web-servers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: httpd:2.4.29
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs
          name: apache2-www
        - mountPath: /usr/local/apache2/logs
          name: apache2-logs
        - mountPath: /usr/local/apache2/conf
          name: apache2-conf
        - mountPath: /mnt
          name: apache2-mnt
      volumes:
      - name: apache2-www
        persistentVolumeClaim:
          claimName: apache2-www
      - name: apache2-logs
        persistentVolumeClaim:
          claimName: apache2-logs
      - name: apache2-conf
        persistentVolumeClaim:
          claimName: apache2-conf
      - name: apache2-mnt
        persistentVolumeClaim:
          claimName: apache2-mnt
      restartPolicy: Always
