apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache2-www
  namespace: web-servers
  labels:
    type: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.224.22.22
    path: "/share/apache2/www/html"
