apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache2-mnt
  namespace: web-servers
  labels:
    app: apache2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 350Gi
