apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-cebas-home
  namespace: build-services
  labels:
    app: jenkins-cebas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
