apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-vus
  namespace: build-services
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenkins-vus
    spec:
      containers:
      - name: jenkins-vus
        image: jenkins
        ports:
          - name: jenkins-vus
            containerPort: 8080
        #env:
        #- name: JENKINS_OPTS
        #  value: --prefix=/jenkins-infrastructure
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1500Mi
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-vus-home
      restartPolicy: Always
