apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-vus-home
  namespace: build-services
  labels:
    app: jenkins-vus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
